//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GameScores {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameScores() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GameScores", typeof(GameScores).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advantage receiver.
        /// </summary>
        public static string AdvantageReceiver {
            get {
                return ResourceManager.GetString("AdvantageReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advantage server.
        /// </summary>
        public static string AdvantageServer {
            get {
                return ResourceManager.GetString("AdvantageServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deuce.
        /// </summary>
        public static string Deuce {
            get {
                return ResourceManager.GetString("Deuce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 all.
        /// </summary>
        public static string FifteenAll {
            get {
                return ResourceManager.GetString("FifteenAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 40.
        /// </summary>
        public static string FifteenForty {
            get {
                return ResourceManager.GetString("FifteenForty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 love.
        /// </summary>
        public static string FifteenLove {
            get {
                return ResourceManager.GetString("FifteenLove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 30.
        /// </summary>
        public static string FifteenThirty {
            get {
                return ResourceManager.GetString("FifteenThirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 15.
        /// </summary>
        public static string FortyFifteen {
            get {
                return ResourceManager.GetString("FortyFifteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 love.
        /// </summary>
        public static string FortyLove {
            get {
                return ResourceManager.GetString("FortyLove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 30.
        /// </summary>
        public static string FortyThirty {
            get {
                return ResourceManager.GetString("FortyThirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game to receiver.
        /// </summary>
        public static string GameToReceiver {
            get {
                return ResourceManager.GetString("GameToReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game to server.
        /// </summary>
        public static string GameToServer {
            get {
                return ResourceManager.GetString("GameToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Love all.
        /// </summary>
        public static string LoveAll {
            get {
                return ResourceManager.GetString("LoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Love 15.
        /// </summary>
        public static string LoveFifteen {
            get {
                return ResourceManager.GetString("LoveFifteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Love 40.
        /// </summary>
        public static string LoveForty {
            get {
                return ResourceManager.GetString("LoveForty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Love 30.
        /// </summary>
        public static string LoveThirty {
            get {
                return ResourceManager.GetString("LoveThirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 all.
        /// </summary>
        public static string ThirtyAll {
            get {
                return ResourceManager.GetString("ThirtyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 15.
        /// </summary>
        public static string ThirtyFifteen {
            get {
                return ResourceManager.GetString("ThirtyFifteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 40.
        /// </summary>
        public static string ThirtyForty {
            get {
                return ResourceManager.GetString("ThirtyForty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 love.
        /// </summary>
        public static string ThirtyLove {
            get {
                return ResourceManager.GetString("ThirtyLove", resourceCulture);
            }
        }
    }
}
